# ================================
# DOCKER COMPOSE SIGB UdM
# Configuration complète pour production
# ================================

version: '3.8'

services:
  # ================================
  # Application SIGB UdM
  # ================================
  sigb-udm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sigb-udm-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Base de données - Configuration exacte de votre .env.local
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=bibliotheque_cameroun
      - DB_HOST=mysql-db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=bibliotheque_cameroun
      # Active Directory - Configuration exacte UdM
      - AD_SERVER=ldap://ad.udm.edu.cm:389
      - AD_PORT=389
      - AD_BASE_DN=DC=udm,DC=edu,DC=cm
      - AD_DOMAIN=UDM
      - AD_ADMIN_USER=administrator@udm.edu.cm
      - AD_ADMIN_PASSWORD=Franck55
      - AD_SERVER_FALLBACK=ldap://192.168.107.52:389
      # JWT - Votre clé exacte
      - JWT_SECRET=udm-sigb-2024-production-jwt-secret-key-very-secure-and-long-for-active-directory-authentication-system-bibliotheque-cameroun
      - JWT_EXPIRES_IN=24h
      # Serveur de fichiers UdM - Configuration exacte
      - FILE_SERVER_HOST=files.udm.edu.cm
      - FILE_SERVER_PORT=21
      - FILE_SERVER_PROTOCOL=ftp
      - FILE_SERVER_USER=bibliotheque-service
      - FILE_SERVER_PASSWORD=Franck55
      - FILE_SERVER_BASE_PATH=/
      - FILE_SERVER_BASE_URL=ftp://files.udm.edu.cm
      - FILE_SERVER_HOST_FALLBACK=192.168.107.52
      - FILE_SERVER_MOCK=false
      # Email SendGrid - Configuration exacte
      - EMAIL_SERVICE=sendgrid
      - EMAIL_API_KEY=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
      - EMAIL_FROM=evriken77@gmail.com
      - EMAIL_FROM_NAME=SIGB UdM
      - EMAIL_NOTIFICATIONS_ENABLED=true
      - EMAIL_REMINDER_DAYS_BEFORE=3
      - EMAIL_OVERDUE_REMINDER_DAYS=1
      # Application
      - NEXT_PUBLIC_APP_NAME=Système de Gestion de Bibliothèque
      - NEXT_PUBLIC_APP_VERSION=1.0.0
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./public/documents:/app/public/documents
      - ./logs:/app/logs
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - sigb-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health/database"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ================================
  # Base de données MySQL
  # ================================
  mysql-db:
    image: mysql:8.0
    container_name: sigb-udm-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=bibliotheque_cameroun
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/bibliotheque_cameroun.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./database/mysql-config.cnf:/etc/mysql/conf.d/custom.cnf:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - sigb-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # ================================
  # Nginx Reverse Proxy (optionnel)
  # ================================
  nginx:
    image: nginx:alpine
    container_name: sigb-udm-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - sigb-udm
    networks:
      - sigb-network
    profiles:
      - with-nginx

# ================================
# Volumes persistants
# ================================
volumes:
  mysql-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/mysql

# ================================
# Réseau interne
# ================================
networks:
  sigb-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
